version: "{build}"

init:
  - git config --global core.autocrlf input

environment:
  DEBUG: 'electron-installer-windows'
  matrix:
    - nodejs_version: "12"
    - nodejs_version: "10"
    - nodejs_version: "8"

platform:
  - x86
  - x64

branches:
  only:
    - master

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:PLATFORM
  - npm install

build: off

before_test:
  - node --version
  - npm --version

test_script:
  - npm test
